export const SET_CUSTOMER = 'SET_CUSTOMER'
export const CLEAR_CUSTOMER_INFO = 'CLEAR_CUSTOMER_INFO'

export const ADD_CUSTOMER_LIST = 'ADD_CUSTOMER'
export const DELETE_CUSTOMER_LIST = 'DELETE_CUSTOMER'

export const COUNT_UP = 'COUNT_UP'